
 development:
  dialect: mariadb
  database: bookings_development
  multiStatements: true
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  pool: 5
  url: {{envOr "DEVELOPMENT_DATABASE_URL" "mysql://root:root@/bookings_development?parseTime=true&multiStatements=true"}}

test:
  dialect: mariadb
  database: bookings_test
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@/bookings_test?parseTime=true&multiStatements=true"}}

production:
  dialect: mariadb
  database: bookings_production
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  url: {{envOr "PRODUCTION_DATABASE_URL" "mysql://root:root@/bookings_production?parseTime=true&multiStatements=true"}}
